0:
  "front_right_hip": 0.5
  "front_left_hip" : -0.5
  "back_left_hip"  : 0.5
  "back_right_hip" : -0.5
  "front_right_leg": 1.0
  "front_left_leg" : 0.7
  "back_left_leg"  : 1.0
  "back_right_leg" : 0.7
  "frames_to_next_keyframe" : 4
1:
  "front_right_hip": -0.5
  "front_left_hip" : 0.5
  "back_left_hip"  : -0.5
  "back_right_hip" : 0.5
  "front_right_leg": 1.0
  "front_left_leg" : 0.7
  "back_left_leg"  : 1.0
  "back_right_leg" : 0.7
  "frames_to_next_keyframe" : 1
2:
  "front_right_hip": -0.5
  "front_left_hip" : 0.5
  "back_left_hip"  : -0.5
  "back_right_hip" : 0.5
  "front_right_leg": 0.7
  "front_left_leg" : 1.0
  "back_left_leg"  : 0.7
  "back_right_leg" : 1.0
  "frames_to_next_keyframe" : 4
3:
  "front_right_hip": 0.5
  "front_left_hip" : -0.5
  "back_left_hip"  : 0.5
  "back_right_hip" : -0.5
  "front_right_leg": 0.7
  "front_left_leg" : 1.0
  "back_left_leg"  : 0.7
  "back_right_leg" : 1.0
  "frames_to_next_keyframe" : 1