0:
  "front_right_hip": 0.0
  "front_left_hip" : 0.0
  "back_left_hip"  : 0.0
  "back_right_hip" : 0.0
  "front_right_leg": 0.9
  "front_left_leg" : 0.9
  "back_left_leg"  : 0.9
  "back_right_leg" : 0.9
  "frames_to_next_keyframe" : 3
