0:
  "front_right_hip": 0.3
  "front_left_hip" : 0.3
  "back_left_hip"  : -0.3
  "back_right_hip" : -0.3
  "front_right_leg": 1.0
  "front_left_leg" : 0.8
  "back_left_leg"  : 1.0
  "back_right_leg" : 0.8
  "frames_to_next_keyframe" : 4
1:
  "front_right_hip": -0.3
  "front_left_hip" : -0.3
  "back_left_hip"  : 0.3
  "back_right_hip" : 0.3
  "front_right_leg": 1.0
  "front_left_leg" : 0.8
  "back_left_leg"  : 1.0
  "back_right_leg" : 0.8
  "frames_to_next_keyframe" : 1
2:
  "front_right_hip": -0.3
  "front_left_hip" : -0.3
  "back_left_hip"  : 0.3
  "back_right_hip" : 0.3
  "front_right_leg": 0.8
  "front_left_leg" : 1.0
  "back_left_leg"  : 0.8
  "back_right_leg" : 1.0
  "frames_to_next_keyframe" : 4
3:
  "front_right_hip": 0.3
  "front_left_hip" : 0.3
  "back_left_hip"  : -0.3
  "back_right_hip" : -0.3
  "front_right_leg": 0.8
  "front_left_leg" : 1.0
  "back_left_leg"  : 0.8
  "back_right_leg" : 1.0
  "frames_to_next_keyframe" : 1
