"actor_config":
  "path": "training_configs/fixed_cycle_configs/fixed_cycle_actor.p"
  "checkpoint_path": "training_configs/actor_checkpoint_fixed_cycle"
  "new_learning_rate": 0.0001
"critic_config":
  "path": "training_configs/fixed_cycle_configs/fixed_cycle_critic.p"
  "new_learning_rate": 0.0002
  "checkpoint_path": "training_configs/critic_checkpoint_fixed_cycle"
"episode_counter_path":
"discount": 0.95
"actor_queue_size": 128
"critic_queue_size": 128
"random_action_prob": 0.4
"noise_std": 0.08
"random_action_prob_half_life": 100
"action_space_size": 8
"phase_steps": 10
"init_step" : 2