"actor_config":
  "path": "AntController/configs/selected_actor_trained_with_noise.p"
  "new_learning_rate": 0.00001
"critic_config":
  "path": "AntController/configs/selected_critic.p"
  "new_learning_rate": 0.00005
"discount": 0.98
"actor_queue_size": 512
"critic_queue_size": 512
"random_action_prob": 0.4
"noise_std": 0.07
"random_action_prob_half_life": 1000
"action_space_size": 8