"actor_config":
  "mlp":
    "layers":
      - "type": "linear"
        "size": 128
      - "type": "relu"
      - "type": "linear"
        "size": 2
      - "type": "softmax"
    "scale": 1
    "shift": 0
  "loss": "squared_loss"
  "rng_key": 42
  "learning_rate" : 0.001
  "decay": 0.999999
  "input_shape": 4
  "name": "actor_cartpole"
"critic_config":
  "mlp":
    "layers":
      - "type": "linear"
        "size": 128
      - "type": "relu"
      - "type": "linear"
        "size": 1
    "scale": 1
    "shift": 0
  "loss": "squared_loss"
  "rng_key": 42
  "learning_rate" : 0.001
  "decay": 0.999999
  "input_shape": 4
  "name": "critic_cartpole"
"discount": 0.9
